### ISSUE TITLE
Run with internal groovy hangs, NB has to be killed

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#11]
When I setup a simple call tyo a user defined class, when running with external groovy it works. When running with bundled Groovy, the IDE hangs and has to be killed.

![](https://user-images.githubusercontent.com/29674819/112840084-3480fb00-909f-11eb-8e24-551741c534ca.png)

**Comment by Enroi** [comment]
You have the symbol - in package name in your scripts. 
It is not allowed. I have such error messages:
![image](https://user-images.githubusercontent.com/15717020/114317829-a67f2880-9b12-11eb-99e4-2cb7511e2ff7.png)

**Comment by Enroi** [comment]
Now after any error in a script, NetBeans can be closed.

**Comment by ouryperd** [comment]
Tested, fixed.
