### ISSUE TITLE
Groovy project doesn't have nbproject folder and contents

### ISSUE THREAD

**Issue by ouryperd** [Enroi/GroovyScripts#8]

**Comment by Enroi** [comment]
nbproject is a folder for Java ANT-based projects.
Maven projects do not have any special folder for project. Maven projects use files nbactions.xml and nb-configuration.xml for store and loading project related data.
Gradle projects have folder gradle. 
Right now current project stores and loads all project-related information in file .netbeans.xml. In this file, I going to save classpath paths.
So I do not see why nbproject folder should be added to this project.

**Comment by ouryperd** [comment]
File .netbeans.xml has all project related parameters
